services:
  - type: web
    name: feature-flag-engine
    runtime: python
    plan: free
    buildCommand: pip install -r server/requirements.txt && cd server && python seed_data.py && cd ..
    startCommand: cd server && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
